### Rotating elements of an array:

In [1]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Visualising what a rotated matrix will look like if original one is rotatd by 90 degrees.

In [4]:
arr_90=np.array([[7,4,1],[8,5,2],[9,6,3]])

In [5]:
arr_90

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [6]:
# np.delete(arr2, 0, 1)

In [7]:
# np.insert(arr2, 0, arr.T[:,2],1)

In [8]:
def rotate_90(arr):
    tran= arr.T
    list1=np.zeros(9)
    arr2= np.asarray(list1).reshape(3,3)
#     print(arr2)
    for i in range(0,3):
        arr2=np.delete(arr2, i, 1)
#         print(arr2.shape)
        arr2=np.insert(arr2, i, tran[:,2-i],1)
#         print(arr2.shape)
    return arr2
rotate_90(arr)

array([[7., 4., 1.],
       [8., 5., 2.],
       [9., 6., 3.]])

In [9]:
rotate_90(arr) == arr_90

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])